apiVersion: apps/v1
kind: Deployment
metadata:
  name: successstory-microservice
  namespace: innovest-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: successstory-microservice
  template:
    metadata:
      labels:
        app: successstory-microservice
    spec:
      containers:
        - name: successstory-microservice
          image: hashiniranaweera/innovest-successstory-microservice:latest
          ports:
            - containerPort: 5007
