apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: broker
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: broker
    spec:
      containers:
        - name: kafka-broker
          image: confluentinc/cp-kafka:7.5.0
          ports:
            - containerPort: 9092
            - containerPort: 29092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: broker
  name: broker
spec:
  ports:
    - name: 9092-9092
      port: 9092
      protocol: TCP
      targetPort: 9092
    - name: 29092-29092
      port: 29092
      protocol: TCP
      targetPort: 29092
  selector:
    app: broker
  type: ClusterIP
status:
  loadBalancer: {}
