apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-microservice
  namespace: innovest-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-microservice
  template:
    metadata:
      labels:
        app: payment-microservice
    spec:
      containers:
        - name: payment-microservice
          image: hashiniranaweera/innovest-payment-microservice:latest
          ports:
            - containerPort: 5003
